ALTER TABLE UniqueItem
ADD COLUMN isChanceable BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE UniqueItem
SET isChanceable = TRUE
WHERE name IN (
    'Shackles of the Wretched',
    'The Covenant',
    'Carnage Heart',
    'Revered Resin',
    'Original Sin',
    'Ming''s Heart',
    'Blackflame',
    'Redflare Conduit',
    'Alpha''s Howl',
    'Dusk Vigil',
    'Lifesprig',
    'Ungil''s Harmony',
    'The Everlasting Gaze',
    'Visage of Ayah',
    'Alkem Eira',
    'The Anvil',
    'Necromantle',
    'Sanguine Diviner',
    'Darkray Vectors',
    'Doomgate',
    'Greymake',
    'Asphyxia''s Wrath',
    'The Infinite Pursuit',
    'Aerisvane''s Wings',
    'Coat of Red',
    'Forbidden Gaze',
    'The Brass Dome',
    'Pariah''s Embrace',
    'Kaom''s Heart',
    'Myris Uxor',
    'The Smiling Knight',
    'Matsya',
    'Feathered Fortress',
    'Idol of Uldurn',
    'Igniferis',
    'Widowhail',
    'Quecholli',
    'The Eternal Spark',
    'Crown of the Pale King',
    'Deathblow',
    'Death''s Harp',
    'The Wailing Wall',
    'Deidbell',
    'Saffell''s Frame',
    'Gamblesprint',
    'Thief''s Torment',
    'Death Rush',
    'Carrion Call',
    'Belly of the Beast',
    'Mask of the Sanguimancer',
    'Bitterbloom',
    'Windscream',
    'Mask of the Stitched Demon',
    'Hoghunt',
    'Goldrim',
    'Shavronne''s Satchel',
    'Maligaro''s Virtuosity',
    'Blackgleam',
    'Grip of Winter',
    'Trephina',
    'Kingsguard',
    'Blackbraid',
    'Plaguefinger',
    'Taryn''s Shiver',
    'Couture of Crimson',
    'Eye of Chayula',
    'Serpent''s Egg',
    'Atziri''s Disdain',
    'Andvarius',
    'Perandus Seal',
    'Ventor''s Gamble',
    'Blueflame Bracers',
    'The Sentry',
    'Erian''s Cobble',
    'Splinter of Loratta',
    'Arvil''s Wheel',
    'Headhunter',
    'Cornathaum',
    'Apron of Emiran',
    'The Hollow Mask',
    'The Black Doubt',
    'Leer Cast',
    'Bronzebeard',
    'Elevore',
    'Powertread',
    'Demon Stitcher',
    'Crown of the Victor',
    'Edyrn''s Tusks',
    'Corpsewade',
    'Blackheart',
    'Voll''s Protector',
    'Defiance of Destiny',
    'Surefooted Sigil',
    'Kitoko''s Current',
    'Crest of Ardura',
    'Prayers for Rain',
    'Radiant Grief',
    'Briarpatch',
    'Ligurium Talisman',
    'Bones of Ullr',
    'Aurseize',
    'Seed of Cataclysm',
    'Doedre''s Damning',
    'Glowswarm',
    'Chober Chaber',
    'Bristleboar',
    'Keelhaul',
    'Killjoy',
    'Bushwhack',
    'Soul Tether',
    'Pillar of the Caged God',
    'Rondel of Fragility',
    'Coward''s Legacy',
    'The Knight-errant',
    'Icetomb',
    'Mist Whisper',
    'Sierran Inheritance',
    'Titanrot Cataphract',
    'Veil of the Night',
    'Atziri''s Acuity',
    'Hrimnor''s Hymn',
    'Rise of the Phoenix',
    'Font of Power',
    'Ryslatha''s Coil',
    'Wulfsbane',
    'Ashrend',
    'Snakepit',
    'Heartbound Loop',
    'Merit of Service',
    'Enfolding Dawn',
    'Infernoclasp',
    'Seeing Stars',
    'The Searing Touch',
    'Foxshade',
    'The Road Warrior',
    'Lycosidae',
    'The Dark Defiler',
    'Meginord''s Girdle',
    'Midnight Braid',
    'Splinterheart',
    'Briskwrap',
    'Jarngreipr',
    'Treefingers',
    'The Barrow Dweller',
    'Gravebind',
    'Legionstride',
    'Blistering Bond',
    'Cracklecreep',
    'Bramblejack',
    'Wings of Caelyn',
    'Horns of Bynden',
    'Dream Fragments',
    'Whisper of the Brotherhood',
    'Polcirkeln',
    'Doryani''s Prototype',
    'The Rat Cage',
    'Idle Hands',
    'Wake of Destruction',
    'Quatl''s Molt',
    'Innsmouth',
    'Husk of Dreams',
    'The Vile Knight',
    'Quill Rain',
    'Guiding Palm',
    'Guiding Palm',
    'Guiding Palm',
    'Oaksworn',
    'Cloak of Flame',
    'Wondertrap',
    'Frostbreath',
    'Wylund''s Stake',
    'Queen of the Forest',
    'Beacon of Azis',
    'Fireflower',
    'Ezomyte Peak',
    'The Three Dragons',
    'Candlemaker',
    'Trenchtimbre',
    'Snakebite',
    'Thrillsteel',
    'Dionadair',
    'Obern''s Bastion',
    'Wandering Reliquary',
    'Nazir''s Judgement',
    'Thunderstep',
    'Astramentis',
    'Fixation of Yix',
    'Doedre''s Tenure',
    'Birth of Fury',
    'The Surrender',
    'Luminous Pace',
    'Brain Rattler',
    'Dustbloom',
    'Northpaw',
    'Ghostwrithe',
    'Lochtonial Caress',
    'Rampart Raptor',
    'Ghostmarch',
    'Serpent''s Lesson',
    'Levinstone',
    'The Burrower',
    'Call of the Brotherhood',
    'Painter''s Servant',
    'The Vertex',
    'Trampletoe',
    'Crown of Thorns',
    'Deathrattle',
    'Greed''s Embrace',
    'Irongrasp',
    'Atsak''s Sight',
    'Ironride',
    'Enezun''s Charge',
    'Earthbound',
    'Tetzlapokal''s Desire',
    'Corona of the Red Sun',
    'Gloomform',
    'The Dancing Mirage',
    'The Devouring Diadem',
    'Brynabas',
    'Birthright Buckle',
    'Skysliver',
    'The Wicked Quill',
    'Nocturne',
    'Brynhand''s Mark',
    'Threaded Light',
    'Black Sun Crest',
    'The Blood Thorn',
    'Wanderlust',
    'Dreadfist',
    'Venopuncture',
    'Window to Paradise',
    'Soul Mantle',
    'Bijouborne',
    'Effigy of Cruelty',
    'Ngamahu''s Chosen',
    'Chainsting',
    'Sire of Shards',
    'The Fallen Formation',
    'Rearguard',
    'The Lethal Draw',
    'Bloodbarrier',
    'Silverthorne',
    'Valako''s Vice',
    'Dunkelhalt',
    'Rondel de Ezo',
    'Cursecarver',
    'Tangletongue',
    'Evergrasping Ring',
    'Stone of Lazhwar',
    'Gloamgown',
    'The Empty Roar',
    'Daevata''s Wind',
    'Gifts from Above',
    'Sculpted Suffering',
    'The Black Insignia',
    'Shyaba',
    'Tyranny''s Grip',
    'Nightscale',
    'Slivertongue',
    'The Prisoner''s Manacles',
    'Goregirdle',
    'Vigilant View',
    'Sands of Silk',
    'Apep''s Supremacy',
    'Saitha''s Spear',
    'Sacrosanctum',
    'Zerphi''s Serape',
    'Silks of Veneration',
    'The Deepest Tower',
    'Waveshaper',
    'Crown of Eyes',
    'The Mutable Star',
    'Redblade Banner',
    'Indigon',
    'Widow''s Reign',
    'Waistgate',
    'Doomfletch',
    'Icefang Orbit',
    'Empire''s Grasp',
    'Essentia Sanguis',
    'Voltaxic Rift',
    'Scold''s Bridle',
    'Tidebreaker',
    'Vis Mortis',
    'The Bringer of Rain',
    'Nebuloch',
    'Cloak of Defiance',
    'Sunsplinter',
    'Yriel''s Fostering',
    'Starkonja''s Head',
    'Prized Pain',
    'Prism Guardian',
    'Leopold''s Applause',
    'Spire of Ire',
    'Rathpith Globe',
    'Mjölner',
    'The Coming Calamity',
    'Hyrri''s Ire',
    'Heatshiver',
    'Chernobog''s Pillar',
    'The Hammer of Faith'
);


