services:
  item-sync-service:
    image: ghcr.io/poe2scout/poe2scout-item-sync:${IMAGE_TAG:-release}
    restart: always
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}

  currency-price-log-service:
    image: ghcr.io/poe2scout/poe2scout-currency-price-log:${IMAGE_TAG:-release}
    restart: "no"
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}
      GrafanaApiToken: ${GRAFANA_API_TOKEN}
      GrafanaEndpoint: ${GRAFANA_ENDPOINT}
      GrafanaInstanceId: ${GRAFANA_INSTANCE_ID}

  currency-item-mapping-service:
    image: ghcr.io/poe2scout/poe2scout-currency-item-mapping:${IMAGE_TAG:-release}
    restart: always
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}
      ApplyChanges: ${CURRENCY_MAPPING_APPLY_CHANGES:-false}
      ApplyCommandTimeoutSeconds: 900
      PollIntervalMinutes: 60
      RePoeRefreshHours: 24

  unique-price-log-service:
    image: ghcr.io/poe2scout/poe2scout-unique-price-log:${IMAGE_TAG:-release}
    restart: "no"
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}
      GrafanaApiToken: ${GRAFANA_API_TOKEN}
      GrafanaEndpoint: ${GRAFANA_ENDPOINT}
      GrafanaInstanceId: ${GRAFANA_INSTANCE_ID}

  currency-exchange-service:
    image: ghcr.io/poe2scout/poe2scout-currency-exchange:${IMAGE_TAG:-release}
    restart: "no"
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}
      GrafanaApiToken: ${GRAFANA_API_TOKEN}
      GrafanaEndpoint: ${GRAFANA_ENDPOINT}
      GrafanaInstanceId: ${GRAFANA_INSTANCE_ID}

networks:
  default:
    name: poe2scout
    external: true
