services:
  old-web:
    image: ghcr.io/poe2scout/poe2scout-old-web:${IMAGE_TAG:-release}
    restart: always
    ports:
      - "127.0.0.1:3001:3000"

  item-sync-service:
    image: ghcr.io/poe2scout/poe2scout-item-sync:${IMAGE_TAG:-release}
    restart: always
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}

  currency-price-log-service:
    image: ghcr.io/poe2scout/poe2scout-currency-price-log:${IMAGE_TAG:-release}
    restart: "no"
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}
      PoeApiClientId: ${POEAPI_CLIENT_ID}
      PoeApiClientSecret: ${POEAPI_CLIENT_SECRET}

  unique-price-log-service:
    image: ghcr.io/poe2scout/poe2scout-unique-price-log:${IMAGE_TAG:-release}
    restart: "no"
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}

  currency-exchange-service:
    image: ghcr.io/poe2scout/poe2scout-currency-exchange:${IMAGE_TAG:-release}
    restart: "no"
    environment:
      DbConnectionString: ${DB_CONNECTION_STRING}
      PoeApiClientId: ${POEAPI_CLIENT_ID}
      PoeApiClientSecret: ${POEAPI_CLIENT_SECRET}

networks:
  default:
    name: poe2scout
    external: true
