global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: item-sync
    metrics_path: /metrics
    static_configs:
      - targets:
          - item-sync-service:9101

  - job_name: currency-price-log
    metrics_path: /metrics
    static_configs:
      - targets:
          - currency-price-log-service:9102

  - job_name: unique-price-log
    metrics_path: /metrics
    static_configs:
      - targets:
          - unique-price-log-service:9103

  - job_name: currency-exchange
    metrics_path: /metrics
    static_configs:
      - targets:
          - currency-exchange-service:9104

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
