apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: discord_webhook
        type: discord
        disableResolveMessage: false
        settings:
          url: $DISCORD_WEBHOOK_URL
          use_discord_username: false
          message: |
            {{ template "default.message" . }}
